### ISSUE TITLE
Question about Track Extension

### ISSUE THREAD

**Issue by toyot-li** [TRI-ML/PF-Track#12]
Hi @ziqipang, I find in the Algorithm B of the Appendix, there exist different updating manners of Query, Center, and Motion during "Track Extension", but in the corresponding part of the code implementation https://github.com/TRI-ML/PF-Track/blob/main/projects/tracking_plugin/models/trackers/runtime_tracker.py#L35-L43, there seems to be only the "living time updating" $L_t$. Am I missing anything important? Or could you please specify where the "Track Extension" is fully implemented in this repo? Thanks.

**Comment by ziqipang** [comment]
@zen-d In addition to what you mentioned, the manipulation of queries happens mainly in (https://github.com/TRI-ML/PF-Track/blob/main/projects/tracking_plugin/models/trackers/spatial_temporal_reason.py). For example, I change the centers of queries with (https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/spatial_temporal_reason.py#L216) and (https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/spatial_temporal_reason.py#L254). 

The utility of `runtime_tracker` or "living time updating" is to keep or remove a query. Specifically, the updates of track extension happen in (https://github.com/TRI-ML/PF-Track/blob/main/projects/tracking_plugin/models/trackers/spatial_temporal_reason.py) and (https://github.com/TRI-ML/PF-Track/blob/main/projects/tracking_plugin/models/trackers/spatial_temporal_reason.py) controls the frame number of extension.

**Comment by ziqipang** [comment]
@zen-d Now I see your concern. Let me put it this way.
* Line 3 of Algo B: The function of [`frame_summarization`](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/tracker.py#L255), which determines if we would like to use the latest information. 
* If the score is high, the query will be covered by `active_mask`. Its reference points, features, and other related fields will be updated by the latest predictions with the prefix `cache_`. This normal propagation part corresponds to Line 14-20 in Algo B.
* For the track extension logic, which is Line 4-12 in Algo B, we are **not explicitly implementing a procedure of accessing previous information**. Instead, the query with low scores are not activated in `active_mask`. Thus, its `track_instances.motion_predictions` automatically keeps the results in the previous frame. See [here](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/tracker.py#LL267C38-L267C38) for how we only update the motion predictions of active queries, and [here](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/spatial_temporal_reason.py#L321) for how we use the previous motion predictions.
* Eventually, for the termination of tracks, which is line 10-13, we use the function in [`runtime_tracker`](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/runtime_tracker.py#L29).
