### ISSUE TITLE
question about visualization

### ISSUE THREAD

**Issue by fatemehazimi990** [TRI-ML/PF-Track#15]
Hi @ziqipang , 

Thanks for releasing the code for your great work! I was wondering where I can find `results.json` file, for mini-set validations to be used for visualization demos. Thanks!

**Comment by ziqipang** [comment]
@fatemehazimi990 Thanks for your question! 

Based on my understanding, this error is not related to `results.json`, but the dataset part. As I don't have the computation to run these experiments after finishing my internship, I suggest you paste the full commands and error messages in this thread so that I can have enough information to help you.

**Comment by fatemehazimi990** [comment]
@ziqipang Thanks for your quick reply. I use the run command `python tools/video_demo/bev.py ./projects/configs/tracking/petr/f3_q500_800x320.py --result work_dir/f3_petr_800x320/results/mini/results_nusc_tracking.json --show-dir ./work_dirs/visualizations/`

I believe it should be an issue with the config. There I see
```
    visualization=dict(type=dataset_type, pipeline=train_pipeline,
              pipeline_multiframe=train_pipeline_multiframe,
              data_root=data_root, test_mode=False,
              classes=class_names, modality=input_modality,
              ann_file=data_root + 'tracking_forecasting-mini_infos_val.pkl',
              num_frames_per_sample=1,)
```
so it uses the train_pipeline for visualization, and test_mode is False. At the same time, it doesnt seem train_pipline provides the expected keys ... Just my guesses :)

**Comment by fatemehazimi990** [comment]
btw the error is `KeyError: 'gt_forecasting_locs'` which happens in this line https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/tools/video_demo/bev.py#L68

**Comment by ziqipang** [comment]
@fatemehazimi990 I see. Your guess is reasonable. In that case, how about you try either of the following ways?
1. Add a `forecasting=True` in the config field of `visualization`, just like the config field for `train` https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/configs/tracking/petr/f3_q500_800x320.py#L108
2. Name a new config pipeline called `visualization_pipeline_multiframe` like below, and replace the `train_pipeline_multiframe` at https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/configs/tracking/petr/f3_q500_800x320.py#L138 with it. Essentially, the fields related to forecasting are removed.
```python
visualization_pipeline_multiframe = [
    dict(type='TrackResizeCropFlipImage', data_aug_conf = ida_aug_conf, training=True),
    dict(type='TrackNormalizeMultiviewImage', **img_norm_cfg),
    dict(type='TrackPadMultiViewImage', size_divisor=32),
    dict(type='FormatBundle3DTrack'),
    dict(type='Collect3D', keys=['points', 'gt_bboxes_3d', 'gt_labels_3d', 'instance_inds', 'img', 'timestamp', 'l2g_r_mat', 'l2g_t', 'l2g'])
]
```

I think the original config of loading gt forecasting was useful when I validated the behavior of my forecasting. But it caused some dirty part in the program.

**Comment by fatemehazimi990** [comment]
Awesome, the first option already solved the problem. Thanks ^^

**Comment by fatemehazimi990** [comment]
solved.
