### ISSUE TITLE
 What is the result.json file in relation to visualization code?

### ISSUE THREAD

**Issue by GHT0320** [TRI-ML/PF-Track#17]
? What is the result.json file in relation to visualization code?
python tools/video_demo/bev.py ./projects/configs/tracking/petr/f3_q500_800x320.py --result results.json --show-dir ./work_dirs/visualizations/

**Comment by ziqipang** [comment]
@GHT0320 Specifically, what do you mean by "in relation to visualization code?"?

**Comment by ziqipang** [comment]
@GHT0320 If you don't have further questions, please kindly close the issue.
