### ISSUE TITLE
about result.json

### ISSUE THREAD

**Issue by GHT0320** [TRI-ML/PF-Track#19]
When I run the visualization code with the command “python tools/video_demo/bev.py ./projects/configs/tracking/petr/f3_q500_800x320.py --result results.json --show-dir ./work_dirs/visualizations/”, I encountered the following error:

Traceback (most recent call last):
  File "tools/bev.py", line 199, in <module>
    main()
  File "tools/bev.py", line 70, in main
    raw_data = dataset[data_info_idx]
  File "/home/guohaotian/PF-Track-main/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 357, in __getitem__
    data = self.prepare_train_data(idx)
  File "/home/guohaotian/PF-Track-main/projects/tracking_plugin/datasets/nuscenes_tracking_dataset.py", line 313, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/guohaotian/anaconda3/envs/PFTrack/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/guohaotian/PF-Track-main/projects/tracking_plugin/datasets/pipelines/pipeline.py", line 470, in __call__
    results = self._load_forecasting(results)
  File "/home/guohaotian/PF-Track-main/projects/tracking_plugin/datasets/pipelines/pipeline.py", line 373, in _load_forecasting
    results['gt_forecasting_locs'] = results['ann_info']['gt_forecasting_locs']
KeyError: 'gt_forecasting_locs'
  0%|      
Looking forward to your reply.

**Comment by ziqipang** [comment]
@GHT0320 Adding a `forecasting=True` in the field of visualization [here](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/configs/tracking/petr/f3_q500_800x320.py#L137).

**Comment by ziqipang** [comment]
@GHT0320 On a second check, my config file of `./projects/configs/tracking/petr/f3_q500_1600x640.py` is correct. You could follow the style here when making the edits.

**Comment by GHT0320** [comment]
> @GHT0320 Adding a `forecasting=True` in the field of visualization in the config file, as in [here](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/configs/tracking/petr/f3_q500_800x320.py#L137).

Thank you very much for your help! But I have one more question, and I saw your demo video on youtube, which shows you the track, where is this code? I ran bev.py and got the following result:
![@UZA0LSVW3K `E3K7EVD%SC](https://github.com/TRI-ML/PF-Track/assets/108056047/c6c451ff-23a8-4d01-b43a-67d6d543fd98)

Your results are as follows:
![}LP@4W46E{S@@6H P1_ MS](https://github.com/TRI-ML/PF-Track/assets/108056047/b0cc5b14-c7ff-4f8c-8980-f99d0baf57bf)

How do I show the trajectory?Do you use other visual code or do you need to change some parameters in bev.py?Looking forward to your reply! Thanks again for your help!

**Comment by ziqipang** [comment]
FYI, the latest commit should also address this issue, exactly the solution presented to you above

**Comment by ziqipang** [comment]
@GHT0320 If you don't have further questions, please kindly close the issue.

**Comment by GHT0320** [comment]
> @GHT0320 If you don't have further questions, please kindly close the issue.

OK,thank for your help again!
