### ISSUE TITLE
Question about the pipeline inputs

### ISSUE THREAD

**Issue by jianingwangind** [TRI-ML/PF-Track#2]
Thanks for sharing the great work!

May i ask that have you tried to use the 3D detection results as network inputs and maybe any denoise techniques as well? Thanks.

**Comment by jianingwangind** [comment]
@ziqipang Thanks for your reply.

I am asking the question because i saw that on NuScenes tracking leaderboard, tracking-by-detection was outperforming query-based tracker like MUTR3D by a large margin and also the success of MOTRv2 in 2D tracking. 
And i have also tried to replace the DETR3D in MUTR3D with PETRhead, but it just didn't work, so really looking forward to have a look at your code :)
Thanks again!

**Comment by ziqipang** [comment]
@jianingwangind This is a good observation: a stronger detector can improve AMOTA, no matter if the tracker is better. I hope my code will help in forming a general interface to adapt query-based detection heads.

**Comment by jianingwangind** [comment]
Sure it will, so code release may happen in middle march? Looking forward to it.

**Comment by jianingwangind** [comment]
@ziqipang regarding to the pseudo code for  track extension, i have two questions:

1. here only frame t-1 is used, but what if observations from frame t-1 are also low-confident, for example for t = 1?
2. If i understand correctly, the key idea here is to update reference points of current frame for low-confident detections based on future predictions from last frame, correct?

**Comment by jianingwangind** [comment]
Thanks for your detailed explanation, and now i understand:)

**Comment by ziqipang** [comment]
@jianingwangind Please check out our latest release. Please also refer to the document of https://github.com/TRI-ML/PF-Track/blob/main/documents/detection_heads.md for integrating with other detection heads.
