### ISSUE TITLE
Evaluaiton on the test set

### ISSUE THREAD

**Issue by toyot-li** [TRI-ML/PF-Track#21]
@ziqipang Hi, thanks for your great work. May I know how to do the evaluation on the nuscenes test set? Thanks.

**Comment by ziqipang** [comment]
@zen-d Replacing the info file of this [line](https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/configs/tracking/petr/f3_q500_1600x640.py#L134) with our `tracking_forecasting_infos_test.pkl` and run `test_tracking.py` just like on the validation set.

**Comment by toyot-li** [comment]
Thanks, I would try that.
