### ISSUE TITLE
for Validation 

### ISSUE THREAD

**Issue by JackHck** [TRI-ML/PF-Track#22]
Why use mutiple GPUs to evaluate only release detection results? how to change it?  Thanks

**Comment by ziqipang** [comment]
@JackHck I am not sure what you want, could you clarify more? If you want to run tracking inference with a single gpu, check this our doc for [inference](https://github.com/TRI-ML/PF-Track/blob/main/documents/inference.md). Hope this helps!

**Comment by JackHck** [comment]
I want to use multiple GPUs to get track inference, but we run the test.py which only releases the detection results.

**Comment by ziqipang** [comment]
@JackHck As tracking has to run sequentially on each frame, we design it to use one GPU. That's also a key difference between tracking and detection. Therefore, the test.py is for detection, and can only be used for detection. 

As far as I know, evaluating tracking on multiple GPUs is difficult, as videos may have different frame numbers. Actually, using one GPU for evaluation is not that slow, ~30min of inference time, if I remember correctly.

**Comment by ziqipang** [comment]
@JackHck Specifically, check this section out [link](https://github.com/TRI-ML/PF-Track/blob/main/documents/designs.md#11-separate-training-and-inference-settings). I think this will clarify a lot.

**Comment by JackHck** [comment]
Thanks for your respond

**Comment by ziqipang** [comment]
@JackHck Hi, if you don't mind, could you please close the issue so that I can better track the questions and respond? Thank you so much!
