### ISSUE TITLE
Gradient checkpointing with ddp

### ISSUE THREAD

**Issue by dsx0511** [TRI-ML/PF-Track#27]
Dear authors,

I'm now working on my own multi-camera tracker with PETR backbone. However, when I enabled the gradient checkpointing(`with_cp=True`) for the `PETRTransformerDecoderLayer` class, I got the error: 

```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 142 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
```

It seems like a conflict between ddp and gradient checkpointing as in many posts. However, setting `find_unused_parameters=False` doesn't help in my case, but `with_cp=False` helps.

I saw in the config files that you provided, you also have set the gradient checkpointing `with_cp=False` everywhere. So I want to know whether you got the same issue when training the tracker? 

Best regards

**Comment by ziqipang** [comment]
@dsx0511 Thanks for the question! To be frank, I debugged this a lot and the following is my personal take-aways.

- Why does checkpointing throw this error? Checkpointing can only be applied to the case where **the parameter is used for only one forward pass.** Therefore, the `PETRTransformerDecoderLayer` is used on $T$ frames in a training sample and caused the above error of checkpointing.
- Where PF-Track applies checkpointing? As mentioned before, I cannot use checkpointing for transformer decoders, but I used it for the VoVNet backbone [code here](https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/configs/tracking/petr/f3_q500_800x320.py#L246).
- Why can I apply this to the backbone? Though the backbone is also forwarded on multiple frames, I integrate the feature extraction on multiple frames in a single run [code](https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/tracking_plugin/models/trackers/tracker.py#L625) to use the checkpointing technique.

Hope the above helps!

**Comment by dsx0511** [comment]
@ziqipang Thank you very much for the detailed answer! It helped me a lot.

I'll only use gradient checkpointing when such a module is fixed during training. But the `PETRTransformerDecoderLayer` is really memory-demanding and it cannot be fixed when training a tracker. So large GPU is always a must :-)

**Comment by ziqipang** [comment]
@dsx0511 Yeah, I agree. I recently learned some tricks, and perhaps they could be helpful:
- Using amp to cast these modules into fp16. The performance might drop, but it won't matter if you are not chasing SOTA.
- If you want to add some modules, maybe you can freeze from my pretrained tracker and finetune your added modules. When I apply PF-Track to high-resolution images, I totally freeze the backbone.

**Comment by yingfei1016** [comment]
@dsx0511 You can use the flash attention and close the gradient checkpointing. The flash attention will save more memory than gradient checkpointing without bug. https://github.com/megvii-research/PETR/blob/flash/projects/mmdet3d_plugin/models/utils/petr_transformer.py#L56

**Comment by dsx0511** [comment]
@yingfei1016 Thank you for mentioning that!
A small question: When I train a PETR model using flash attention in the decoder layer, can I directly restore the weights from a checkpoint in your model zoo, that is trained with normal attention?

**Comment by yingfei1016** [comment]
@dsx0511 
I think is OK.
We not do this experiment, but we tried to train a model with flash attention, and then used normal attention when testing. In this case, the performance is the same, so I feel that the reverse process can also be done.
