### ISSUE TITLE
About the tracking result

### ISSUE THREAD

**Issue by goahence** [TRI-ML/PF-Track#28]
Hello, I am an undergraduate student. Recently I have been studying algorithms related to motion prediction. I hope to experiment with my own algorithm using the tracking results. Could you please provide the verification results of your algorithm on Nuscenes? If you can provide relevant help, thank you sincerely.

**Comment by ziqipang** [comment]
@goahence Thank you for your interest! Plese check out this section https://github.com/TRI-ML/PF-Track/blob/main/documents/pretrained.md#2-pretrained-pf-track-models-download

**Comment by goahence** [comment]
Thanks! I found it.

**Comment by goahence** [comment]
Hi, sorry to bother you again. I'd like to know how long your model takes per image to perform inference and what hardware you're using for your model. Thanks for answering.

**Comment by ziqipang** [comment]
@goahence I cannot remember correctly since it was more than one year ago. My vague memory is that: suppose you are using one A100 and running at the full-resolution setting, it should be quicker than 2 FPS and the whole inference will be completed in around 1 hour.

**Comment by goahence** [comment]
Got it! Thanks!
