### ISSUE TITLE
Get some Errors when test tracking method

### ISSUE THREAD

**Issue by hanzifan** [TRI-ML/PF-Track#29]
I got some errors when I tested the tracking.

My environment is a little bit different from the environment which is provided. My MMCV is version mmcv-full==1.6.0, my mmdet is version 2.28.2, my mmdet3d is version 1.0.0rc6. Also, my torch version is 1.13.1.

I could train and validate. However, when I tried to test tracking, I got this bug.
```
KeyError: 'NuScenesTrackingDataset is not in the dataset registry'
```

**Comment by ziqipang** [comment]
@hanzifan Do you have a full log of the errors? It looks strange to me because the training of the model also requires `NuScenesTrackingDataset`. While you generate the error log, I suggest keeping everything consistent between the training and testing (e.g. locations to run the code).

**Comment by hanzifan** [comment]
Sorry for my late reply.
Here's my full log of errors.
![1711099900356](https://github.com/TRI-ML/PF-Track/assets/43206681/70176245-bd2a-49f4-9764-934dd48bdcd0)
Here's my training log
![1711100171961](https://github.com/TRI-ML/PF-Track/assets/43206681/a0aff0b6-d586-43f9-8371-bf3120174b30)
![1711100201669](https://github.com/TRI-ML/PF-Track/assets/43206681/612f12a9-31a5-44ec-9cc5-2ba1fddbb4b9)
Here's my training command
![1711100394300](https://github.com/TRI-ML/PF-Track/assets/43206681/16c09296-88a5-4559-8bce-ef4aba591490)

**Comment by ziqipang** [comment]
@hanzifan What about adding a `PYTHONPATH=./` before the command for the test?

**Comment by hanzifan** [comment]
Thanks, that's work for me.
