### ISSUE TITLE
detection_head

### ISSUE THREAD

**Issue by miraclesheephaha** [TRI-ML/PF-Track#31]
I want to put the detection_head of petrv2 into it. During the training process, this problem occurred: TypeError: forward() takes 3 positional arguments but 6 were given. Does forward() in petrv2_head.py need to change the number of parameters?
Looking forward to your answer,thank you.

**Comment by ziqipang** [comment]
@miraclesheephaha I am not familiar with PETRv2 right now. From the error message you just presented, it seems you have to modify the input arguments of each type of class. For the tracking purpose, I think the input to the head needs to be modified. For example, you can take a look at how I modified the things and perhaps imitate this style if you want to use PETRv2.
* [Here](https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/tracking_plugin/models/dense_heads/petr_tracking_head.py#L278) is my modified PETR head for tracking.
* [Here](https://github.com/megvii-research/PETR/blob/f7525f93467a33707ef401c587a52d5e7b34de74/projects/mmdet3d_plugin/models/dense_heads/petr_head.py#L359) is the original PETR head.

**Comment by miraclesheephaha** [comment]
OK,Thank you for your reply.
I will try it.

**Comment by ziqipang** [comment]
@miraclesheephaha Also, please check our documentation out to see if its information helps. https://github.com/TRI-ML/PF-Track/blob/main/documents/detection_heads.md

**Comment by miraclesheephaha** [comment]
After that, I created new petrv2_tracking_head2 and petrv2's f1_q500_800*320.py, and then I added the following line to train_pipeline_multiframe in f1_q500_800*320.py
`dict(type='LoadMultiViewImageFromMultiSweepsFiles', sweeps_num=1, to_float32=True, pad_empty_sweeps=True, test_mode=False, sweep_range=[3,27])
`
According to this question, I also added generate_sweep_pkl.py of petrv2
https://github.com/megvii-research/PETR/issues/60

This problem will occur as follows
`PF-Track/projects/mmdet3d_plugin/datasets/pipelines/loading.py", line 63, in __call__
    img_timestamp = results['img_timestamp']
KeyError: 'img_timestamp'`

Looking forward to your answer,thank you.

**Comment by ziqipang** [comment]
From the error message, it seems you are not using the tracking dataset, not sure if it is related, example [link](https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/configs/tracking/petr/f3_q500_800x320.py#L30). Meanwhile, please also remember to prepare the data according to my documentation. @miraclesheephaha
