### ISSUE TITLE
nuscenes_dataset

### ISSUE THREAD

**Issue by hibernationT** [TRI-ML/PF-Track#32]
Hello, I ran into a problem while running the test_tracking using "python tools/test_tracking.py projects/configs/tracking/petr/f3_q500_800x320.py ./work_dir/f3_petr_800x320/final.pth --jsonfile_prefix ./work_dir/f3_petr_800x320/results --eval bbox". The problem is "RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 6-dimensional input of size [1, 1, 6, 3, 320, 800] instead".Looking forward to your answer,thank you.
![issue](https://github.com/TRI-ML/PF-Track/assets/84330888/67efda8c-5e7c-4262-a19e-c27f87223078)

**Comment by ziqipang** [comment]
@hibernationT Thanks for your question! It is unfortunate that I don't have GPU resources to run PF-Track right now. So I might request more information from you to debug. As a beginning, could you check the following things:
* I seems your environment does not have a cuda, is this related?
* The shape of the input image sounds weird, and the other hasn't experienced this problem before. If you haven't changed anything to the code, could you check if the input image has the shape consistent with this line [link](https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/tracking_plugin/models/trackers/tracker.py#L662)?
