### ISSUE TITLE
Question about LIDAR point clouds usage

### ISSUE THREAD

**Issue by Tlx2208** [TRI-ML/PF-Track#40]
Hi, thanks for the great work!

I am trying to apply PF-Track in a situation without LIDAR.

At first I thought that only camera sensors are used, as mentioned in the paper.

However, after going through the code it seems that the LIDAR point clouds are always required for SpatialTemporalReasoner to update the position.

It also seems that previous work DETR3D, which claimed to not use point clouds in the paper, also seems to require point clouds for the feature sampling method.

May I know did I understand it wrongly? If so, is there any modifications I can make for them to work on a purely camera only system?

Thanks.

**Comment by Tlx2208** [comment]
It seems that I misunderstood the code wrongly. I was referring to the lidar2img values in img_metas, and that I misunderstood them as the point cloud data. But they are just projection matrix from the world coordinates to the image point thus no point cloud is used.

Closing the issue for now, but feel free to correct me if I am wrong.

**Comment by NATHANCHU-a11y** [comment]
Hi, I'm also trying to use the model with camera data only. However, I'm encountering an issue during preprocessing—it seems that I can't preprocess the dataset without metadata. My goal is to use the test data for inference first, without relying on the metadata.

Could you please share how you handled preprocessing in a similar scenario? Any guidance or suggestions would be greatly appreciated.

Thank you!
