### ISSUE TITLE
Thanks for the great Works! I would like to ask if it is possible to modify this work input to point cloud

### ISSUE THREAD

**Issue by ellen19967** [TRI-ML/PF-Track#7]

**Comment by ziqipang** [comment]
@ellen19967 Thanks for your interest! I haven't tried this before, but I think it is possible. I think the main job is to change `extract_img_feat` to a LiDAR-based backbone in mmdetection3d and change `pts_bbox_head` to a LiDAR-based detection head.

**Comment by ziqipang** [comment]
These are the things I would try, please use them as a reference and you can surely come up with better plans.

**Comment by ellen19967** [comment]
Many thanks!
