### ISSUE TITLE
Question about motion prediction

### ISSUE THREAD

**Issue by jianingwangind** [TRI-ML/PF-Track#8]
The code structure is really elegant!

And i have a question w.r.t. motion prediction/ref points update:

the reference points is updated twice in tracker.py with motion predictions and ego movements respectively, meaning the predicted motion is defined in the current frame coordinate system?

**Comment by ziqipang** [comment]
@jianingwangind Yes. I remembered that the predictions are $(\Delta x, \Delta y)$ located in the local sensor coordinate.

**Comment by jianingwangind** [comment]
Thanks a lot.

**Comment by jianingwangind** [comment]
Another question maybe...

In history refine, ref points and bboxes are updated and they are used to update the corresponding cache_xxx, but why not update the ones in history bank? I saw you just comment them.

**Comment by ziqipang** [comment]
@jianingwangind I evaluated the code before releasing the code, but I didn't remember and notice what you mentioned, to be honest. I guess the current implementation considers that a bounding box with a low score shouldn't fit into history. Thus, the predictions will not be `hist_xxx` directly.

However, I cannot deny that your suggestion is also reasonable. As I don't have enough computation right now, do you mind uncommenting Line 135 and 138 of `spatial_temporal_reasoner.py` and see how things will go?

**Comment by jianingwangind** [comment]
Sure, thanks for your reply:)
